config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'main#index'

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  get 'signup', to: 'registrations#new'
  post 'signup', to: 'registrations#create'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'about-us', to: 'about#index', as: :about

  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/twitter_account.rb
# frozen_string_literal: true

class TwitterAccount < ApplicationRecord
  belongs_to :user

  validates :username, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

# email:string
# password_digest:string

class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: 'must be valid email address' },
                    uniqueness: true
  has_many :twitter_accounts
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to signin_path, alert: 'You need to be signed in' if Current.user.nil?
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index; end
end

app/controllers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class OmniauthCallbacksController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret
    )
    redirect_to twitter_accounts_path, notice: 'Succesfully connected your account'
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    PasswordMailer.with(user: @user).reset.deliver_now if @user.present?
    redirect_to root_path, notice: 'Check email inbox for reset instructions'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to signin_path, alert: 'Your token has expired'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to signin_path, notice: 'Password reset successfully'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit; end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password updated'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Succesfully created an account'
    else

      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    # @session = .new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Invalid authentication data'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/twitter_accounts_controller.rb
# frozen_string_literal: true

class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: %i[show destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def show; end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ScheduledTweets</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'shared/navbar' %>
    <div class="container">
        <%= render 'shared/flash' %>
        <%= yield %>
    </div>
</body>

</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome To Scheduled Tweets</h1>


</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

<% if form.object.errors.any? %>
<div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
    <div class=""><%= message %></div>
    <% end %>
</div>
<% end %>

<div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password,
                            class: 'form-control',
                            placeholder: 'Password'%>
</div>

<div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation,
                            class: 'form-control',
                            placeholder: 'Password' %>
</div>

<div class="mb-3">
    <%= form.submit 'Reset Password', class: 'btn btn-secondary' %>
</div>

<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
<div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email,
                        class: 'form-control',
                        placeholder: 'chucknorris@texas.us' %>
</div>

<div class="mb-3">
    <%= form.submit 'Reset Password', class: 'btn btn-secondary' %>
</div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <%= link_to 'Scheduled Tweets', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to 'Home', root_path, class: 'nav-link active' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Twitter Accounts', twitter_accounts_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'About', about_path, class: 'nav-link' %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if Current.user %>
                <li class="nav-item">
                    <%= link_to Current.user.email, edit_password_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= button_to 'Log out', logout_path,
                         method: :delete,
                         class: 'btn btn-danger' %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Log In', signin_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
    <h1>Twitter Accounts</h1>

    <%= link_to 'Connect a Twitter account',
                               '/auth/twitter',
                               class: 'btn btn-primary' %>
</div>
<% @twitter_accounts.each do |account| %>
<div class="d-flex align-items-center mb-4">
    <div class="me-4">
        <%= image_tag account.image, class: 'rounded-circle' %>
        <%= link_to "#{account.username}",
        "https://twitter.com/#{account.username}",
        target: :blank %>
    </div>

    <%= button_to 'Disconnect', account, method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-danger btn-sm' %>
</div>
<% end %>